name: Amrita ~ Elixir of Life
favicon: null
layout_spectrum: 0.6161986028309911
typography_spectrum: 0.7644771246705204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.24681578134186566
  lightness: 0.18896863237023354
  saturation: 0.023410805268213153
  rhythmicContrast: 0.7684804326854646
purpose: []
